language: python

python:
  - 3.7

dist: xenial

services:
  - docker

before_install:
  - git fetch origin +refs/heads/$TRAVIS_BRANCH

install:
  - pip install -r requirements.txt

matrix:
  include:
    - name: "presubmit"
      script: make presubmit
